---
title: "Semester B"
description: ""
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Lectures

### 1. 16/03/2021, Getting back into R with messy data

- [HTML Slides](slides/Week-23-messy-data.html)
- [PDF Slides](slides/B-1-messy-data.pdf)

### 2. 23/03/2021, Statistical power and effect sizes
- [HTML Slides](slides/2-Power-and-Effect-Sizes.html)
- [PDF Slides](slides/2-Power-and-Effect-Sizes.pdf)

### 3. 13/04/2021, Multiple and logistic regression
- [HTML Slides](slides/3-generalized-linear-models.html)
- [PDF Slides](slides/3-generalized-linear-models.pdf)

### 4. 20/04/2021, Multilevel analysis
- [HTML Slides](slides/4-multilevel-modelling.html)
- [PDF Slides](slides/4-multilevel-modelling.pdf)

### 5. 27/04/2021, Moderation and Mediation
- [HTML Slides](slides/5-Moderation-Mediation.html)
- [PDF Slides](slides/5-Moderation-Mediation.pdf)

### 6. 04/05/2021, Factor analysis
- [HTML Slides](slides/6-Factor-Analysis.html)
- [PDF Slides](slides/6-Factor-Analysis.pdf)

### 7. 11/05/2021, Statistics done wrong
- [HTML Slides](slides/7-stats-done-wrong.html)
- [PDF Slides](slides/7-stats-done-wrong.pdf)

### 8. 18/05/2021, R from start to finish
- [HTML Slides](slides/8-R-from-start-to-finish.html)
- [PDF Slides](slides/8-R-from-start-to-finish.pdf)
